import type { ReactNode } from "react";

export const batch10Content: Record<string, ReactNode> = {
  "who-owns-ai-generated-contractor-work": (
    <>
      <p>You hired a designer to build a logo. The contract says the work is a work made for hire, and to the extent it is not, the contractor assigns all rights to you. Your lawyer drafted it. It is a good clause.</p>

      <p>The designer used an AI image generator. And the clause, drafted correctly and signed by everyone, may have transferred nothing at all.</p>

      <p>This is not a drafting failure. It is a gap between two bodies of law that most contractor agreements were written before anyone needed to think about. Understanding it takes about ten minutes and changes what you should put in your next agreement.</p>

      <h2>Why the clause fails</h2>

      <p>Start with what an assignment does. An assignment transfers an existing property right from one party to another. If the right does not exist, the assignment moves nothing. It is not void, and it is not badly drafted &mdash; it simply operates on an empty set.</p>

      <p>Copyright in the United States requires human authorship. The Copyright Office has held this consistently, and the federal courts have agreed: a work generated by a machine without human creative control over the expression is not protected by copyright, and no one owns it. It is not that the contractor owns it and failed to transfer it. Nobody owns it. Anyone can copy it.</p>

      <p>So when a contractor delivers output generated substantially by an AI system, your assignment clause reaches for a right that was never created.</p>

      <p>The work-made-for-hire language has a separate problem worth knowing about even apart from AI. Under <a href="https://www.law.cornell.edu/uscode/text/17/101" target="_blank" rel="noopener noreferrer">17 U.S.C. &sect; 101</a>, a work by an independent contractor qualifies as a work made for hire only if it falls into one of nine enumerated categories and the parties sign a written agreement saying so. A logo, a website, most marketing copy, and most custom software do not fall in those categories. This is why competent agreements pair the work-for-hire recital with a backup assignment &mdash; the assignment is usually the clause doing the actual work. Which is precisely the clause the AI problem disables.</p>

      <h2>What is actually protectable</h2>

      <p>The rule is not that AI involvement destroys protection. It is that protection attaches to human creative contribution and nothing else.</p>

      <p>The Copyright Office has registered works that incorporate AI-generated material where a human selected, arranged, and modified the output in creative ways &mdash; but the registration covers the human contribution, not the AI-generated elements. A person who generates a hundred images, selects one, substantially reworks it, and combines it with original elements has a much stronger position than one who typed a prompt and accepted the result. Prompting alone, however elaborate, has generally not been treated as sufficient authorship over the resulting expression.</p>

      <p>The practical consequence is that the answer depends on facts you do not currently have, because you were not there when the work was made and your contract never required anyone to write it down.</p>

      <h2>Where this bites hardest</h2>

      <p><strong>Brand assets.</strong> A logo you cannot protect by copyright is the most common version of this problem, and also the one with the best backup. Copyright and trademark are separate systems. Even if copyright in the logo is unavailable, trademark rights arise from use of the mark as a source identifier, and a federal registration through the <a href="https://www.uspto.gov/trademarks" target="_blank" rel="noopener noreferrer">USPTO</a> does not require copyright. A competitor who copies your logo to sell competing goods still faces an infringement claim. What you lose is the ability to stop non-competing reproduction of the image itself. That is a real loss, and it is narrower than most owners fear. See <a href="/blog/how-to-protect-your-business-name">protecting your business name</a> and <a href="/blog/trademark-registration">trademark registration</a> for what that path involves.</p>

      <p><strong>Content you built a strategy around.</strong> Articles, guides, and image libraries commissioned as a content asset are worth what their exclusivity is worth. Unprotectable content can be copied verbatim by a competitor, and your only response is that it was unkind.</p>

      <p><strong>Software.</strong> AI-assisted code raises the ownership question and a second one alongside it: whether output reproduces material from training data under a license you have not complied with. The ownership issue is about what you have. The second is about what you might owe.</p>

      <h2>Fixing the agreement</h2>

      <p>Five additions handle nearly all of it, and none require rewriting the contract.</p>

      <p><strong>Disclosure.</strong> Require the contractor to disclose in writing whether AI tools were used in creating deliverables, which tools, and for what. Make it a continuing obligation, not a one-time question at signing.</p>

      <p><strong>A representation about human authorship.</strong> For deliverables where protection matters &mdash; brand assets, anything you will register, anything central to the business &mdash; require the contractor to represent that the work reflects their own creative authorship. If they cannot make that representation, you want to know before you build a brand on it.</p>

      <p><strong>A documentation requirement.</strong> Require records showing the human creative contribution: drafts, iterations, the selection and modification decisions made. This is what a registration application or a later dispute will turn on, and it cannot be reconstructed after the fact.</p>

      <p><strong>Keep the assignment, and add a waiver.</strong> The assignment still does necessary work for everything that is protectable. Nothing here is a reason to remove it.</p>

      <p><strong>Indemnification for third-party IP claims.</strong> The ownership gap and the infringement risk are different problems, and indemnity addresses the second. Note that indemnity is only as good as the contractor&apos;s ability to pay it &mdash; against a solo freelancer it is worth less than it reads. See <a href="/blog/what-should-be-in-every-business-contract">what belongs in every business contract</a> and the <a href="/blog/contractor-agreement">contractor agreement</a> essentials.</p>

      <h2>Work already delivered</h2>

      <p>Inventory the assets that actually matter &mdash; usually a short list. Ask the contractors who made them whether AI was involved, in writing, without making it sound like an accusation; most will simply tell you. For anything central where the answer is yes or unknown, you have three options: document whatever human contribution exists and register on that basis, have the asset re-created under an agreement that closes the gap, or rely on trademark rather than copyright where the asset is a brand mark. For a logo, the third option is usually enough.</p>

      <h2>Frequently Asked Questions</h2>

      <h3>If my contractor used AI, do I own the deliverable?</h3>
      <p>You own whatever copyright exists, which may be nothing. If the work was generated substantially by AI without human creative control over the expression, no copyright arose, and an assignment transfers nothing. Where a human made meaningful creative decisions, protection attaches to that contribution and your assignment reaches it.</p>

      <h3>Does a work-made-for-hire clause solve this?</h3>
      <p>No, and it has its own limits. Contractor work qualifies as work made for hire only within nine statutory categories that exclude most logos, websites, and custom software. That is why agreements include a backup assignment &mdash; and the assignment is subject to the same problem, because it can only transfer a right that exists.</p>

      <h3>Can I still register the copyright?</h3>
      <p>Sometimes. Applicants must disclose AI-generated content and disclaim it, and the registration covers the human contribution. Where a person selected, arranged, and modified AI output creatively, that contribution can support registration. Claiming AI-generated material as your own authorship is a misrepresentation to the Copyright Office and can invalidate the registration.</p>

      <h3>Does this mean I could lose my logo?</h3>
      <p>Not in the way most people fear. Trademark rights are separate from copyright and arise from use of a mark as a source identifier. A competitor using a confusingly similar mark on competing goods still faces a trademark claim. What weakens is your ability to stop reproduction of the image outside that context.</p>

      <h3>What should I add to my contractor agreement now?</h3>
      <p>Disclosure of AI use, a human-authorship representation for deliverables that matter, a requirement to keep records of creative contribution, the existing assignment, and indemnification for third-party IP claims. Five clauses, none long.</p>

      <p>This is one piece of a wider set of exposures that arrive with AI adoption &mdash; hiring tools and disclosure obligations among them. See <a href="/blog/when-is-my-business-liable-for-ai">when your business is liable for AI</a> for how courts are currently allocating that liability, and <a href="/blog/employee-ai-use-policy">the employee AI use policy</a> for governing AI use inside your own team.</p>
    </>
  ),
};
