import type { BlogPost } from "./blogTypes";

// Metadata for all 38 blog articles, assembled from the Phase 4 conversion
// batches. Category labels were normalized here to the canonical 12-volume
// taxonomy ("<Volume Title> — Book <N>") — the source HTML used at least four
// different phrasings ("Volume N", "From Volume N", "Book N", plus several
// off-taxonomy labels like "Risk Management" or "Exit Strategy") depending on
// which of ~5 distinct article templates each piece was originally built from.
export const blogPosts: BlogPost[] = [
  {
    slug: "1099-vs-w2-worker-classification",
    title: "1099 vs W-2: When Worker Misclassification Will Cost You Six Figures",
    category: "Building Your Team — Book 5",
    excerpt: "The IRS, the DOL, and state agencies use three different tests to classify workers, and they don't always agree. Why most contractor classifications fail under audit, and what the back-tax math actually looks like.",
    date: "2026-04-27",
    relatedBook: {
      title: "The Entrepreneur's Guide to Building Your Team — Book 5",
      description: "Worker classification, hiring law, employment agreements, restrictive covenants, equity compensation, and the legal foundation for bringing people into your business. Part of The Million Dollar Highway series from Silverton Publishing.",
    },
  },
  {
    slug: "ai-tools-small-business-legal",
    title: "AI Tools in Your Small Business: Practical Use Without Legal Exposure",
    category: "Technology, AI & Digital Business — Book 7",
    excerpt: "AI tools are accelerating small business productivity. Here's where the legal exposure actually lives — and how to use AI aggressively without getting burned.",
    date: "2026-07-07",
  },
  {
    slug: "biggest-tax-mistakes-new-business",
    title: "The 5 Biggest Tax Mistakes New Business Owners Make",
    category: "Tax Planning & Accounting — Book 3",
    excerpt: "Five costly tax mistakes entrepreneurs make in year one — mixing personal and business money, ignoring quarterly estimated taxes, misclassifying workers, and more. How to avoid them.",
    date: "2026-03-31",
  },
  {
    slug: "business-insurance-claims",
    title: "Business Insurance Claims: What Small Business Owners Get Wrong",
    category: "Business Insurance & Risk Management — Book 4",
    excerpt: "Having business insurance and making effective use of it are two different things. The most common and costly mistakes small business owners make when filing claims — and the practices that prevent them.",
    date: "2026-06-30",
  },
  {
    slug: "business-insurance-types-guide",
    title: "Business Insurance: What Coverage Your Small Business Actually Needs",
    category: "Business Insurance & Risk Management — Book 4",
    excerpt: "General liability, professional liability, BOP, workers' comp, cyber, D&O — which types of business insurance your small business needs and what each covers.",
    date: "2026-08-09",
  },
  {
    slug: "business-succession-planning",
    title: "Building a Business Succession Plan Before You Need One",
    category: "Selling Your Business — Book 11",
    excerpt: "Succession planning isn't morbid — it's business continuity planning, exit value optimization, and personal financial planning all at once. Starting five years early is almost always the right move.",
    date: "2026-07-14",
  },
  {
    slug: "contractor-agreement",
    title: "What Actually Belongs in an Independent Contractor Agreement",
    category: "Contracts & Legal Foundations — Book 2",
    excerpt: "The IRS reclassifies thousands of independent contractors as employees every year. The difference between a legitimate 1099 relationship and a misclassification disaster often comes down to whether your contractor agreement includes the right clauses.",
    date: "2026-05-26",
    relatedBook: {
      title: "Contracts & Legal Foundations — Book 2",
      description: "A clause-by-clause deep dive into every contract provision entrepreneurs encounter, with practical negotiation guidance for each. Part of The Million Dollar Highway series from Silverton Publishing.",
    },
  },
  {
    slug: "do-i-need-a-business-lawyer",
    title: "Do I Actually Need a Business Lawyer, or Can I Just Use LegalZoom?",
    category: "Business Structure & Contracts — Books 1 & 2",
    excerpt: "Should you hire a business lawyer or use an online service like LegalZoom? A practicing attorney breaks down when you actually need legal help — and when you're fine on your own.",
    date: "2026-03-31",
  },
  {
    slug: "earnout-clauses-selling-business",
    title: "Earnout Clauses When Selling Your Business: What They Are and Why They're Dangerous",
    category: "Selling Your Business — Book 11",
    excerpt: "Earnouts appear in deals as a bridge mechanism between seller valuation and buyer price. In practice, they generate more post-closing disputes than almost any other acquisition term.",
    date: "2026-06-30",
    relatedBook: {
      title: "Volume 11: Selling Your Business",
      description: "Covering valuation, deal structure, reps and warranties, earnouts, and what happens in the years after a sale.",
    },
  },
  {
    slug: "financing-business-acquisition",
    title: "Financing a Business Acquisition: What Lenders Actually Look At",
    category: "Business Financing — Book 9",
    excerpt: "Business acquisition lenders are underwriting two things simultaneously: the business being acquired and the buyer's ability to operate it. Understanding what they look at helps you present a stronger loan package.",
    date: "2026-06-30",
    relatedBook: {
      title: "Volume 9: Business Financing",
      description: "Covering debt, equity, seller notes, and acquisition financing structures.",
    },
  },
  {
    slug: "how-to-buy-a-small-business",
    title: "How to Buy a Small Business: Due Diligence, Deal Structure, and What Can Go Wrong",
    category: "Buying a Business — Book 10",
    excerpt: "Thinking about buying a small business? A practical guide to due diligence, asset vs stock purchase, deal structure, SBA loans, and the red flags that kill acquisitions.",
    date: "2026-03-31",
    relatedBook: {
      title: "Volume 10: Buying a Business",
      description: "Covering deal sourcing, valuation methods, due diligence checklists, deal structure, SBA financing, purchase agreements, and post-closing integration.",
    },
  },
  {
    slug: "how-to-fire-an-employee-legally",
    title: "How to Fire an Employee Without Getting Sued",
    category: "Managing Your Team — Book 6",
    excerpt: "At-will employment doesn't mean consequence-free termination. How to fire an employee legally — documentation, progressive discipline, final paycheck rules, and the mistakes that lead to lawsuits.",
    date: "2026-03-31",
    relatedBook: {
      title: "Volume 6: Managing Your Team",
      description: "Covering performance management, progressive discipline, termination procedures, severance agreements, and the full legal framework for managing and separating from employees.",
    },
  },
  {
    slug: "how-to-handle-eeoc-complaint",
    title: "How to Handle an EEOC Complaint Against Your Small Business",
    category: "Managing Your Team — Book 6",
    excerpt: "What happens when an employee files an EEOC complaint against your small business: the investigation process, your response obligations, mediation, and how to minimize legal exposure.",
    date: "2026-08-09",
  },
  {
    slug: "how-to-hire-your-first-employee",
    title: "How to Hire Your First Employee Without Breaking the Law",
    category: "Building Your Team — Book 5",
    excerpt: "A step-by-step legal guide to hiring your first employee. EIN, W-4, I-9, workers comp, payroll taxes, and the mistakes that get small businesses fined. Written by a practicing attorney.",
    date: "2026-03-31",
    relatedBook: {
      title: "Volume 5: Building Your Team",
      description: "Covering classification, hiring, onboarding, compensation structures, payroll setup, and the complete legal framework for becoming an employer.",
    },
  },
  {
    slug: "how-to-legally-terminate-employee",
    title: "How to Legally Terminate an Employee: A Small Business Owner's Guide",
    category: "Managing Your Team — Book 6",
    excerpt: "The legal steps for terminating an employee in an at-will state: documentation requirements, final pay timing, COBRA notice, WARN Act basics, and what to avoid.",
    date: "2026-08-09",
  },
  {
    slug: "how-to-prepare-business-for-sale",
    title: "How to Prepare Your Business for Sale: The 18-Month Exit Checklist",
    category: "Selling Your Business — Book 11",
    excerpt: "Most business owners start preparing to sell six months too late. Here is the 18-month checklist that maximizes your valuation, reduces buyer risk, and gets deals closed—from an attorney who has been on both sides of the table.",
    date: "2026-04-06",
    relatedBook: {
      title: "The Entrepreneur's Guide to Selling Your Business — Book 11",
      description: "Valuation, deal structure, due diligence preparation, LOI negotiation, purchase agreement terms, representations and warranties, and post-closing obligations. Part of The Million Dollar Highway series from Silverton Publishing.",
    },
  },
  {
    slug: "how-to-protect-your-business-name",
    title: "How to Protect Your Business Name: Trademarks, Domains, and What Most Founders Get Wrong",
    category: "Intellectual Property — Book 8",
    excerpt: "Registering a business name isn't the same as protecting it. Learn how trademarks, domain names, and common law rights actually work — and what most founders get wrong about business name protection.",
    date: "2026-03-31",
    relatedBook: {
      title: "Intellectual Property — Book 8",
      description: "Covering trademarks, copyrights, patents, trade secrets, domain strategy, cybersquatting, and the full IP toolkit every entrepreneur needs.",
    },
  },
  {
    slug: "how-to-read-commercial-lease",
    title: "How to Read a Commercial Lease Before You Sign",
    category: "Contracts & Legal Foundations — Book 2",
    excerpt: "Commercial leases are among the most consequential documents a small business owner will sign — and they're frequently signed without the scrutiny they deserve. What to examine before your signature binds you for years.",
    date: "2026-06-30",
    relatedBook: {
      title: "Contracts & Legal Foundations — Book 2",
      description: "Covering the full range of contracts that govern small business operations, including commercial leases, vendor agreements, and customer contracts.",
    },
  },
  {
    slug: "how-to-sell-your-business",
    title: "How to Sell Your Business: Timing, Valuation, and Exit Strategy",
    category: "Selling Your Business — Book 11",
    excerpt: "When should you sell your business, and how do you get the best price? A practical guide to exit timing, business valuation, buyer types, deal structure, and tax planning for business sales.",
    date: "2026-03-31",
    relatedBook: {
      title: "Selling Your Business — Book 11",
      description: "Covering exit timing, valuation frameworks, buyer identification, deal structure, tax optimization, purchase agreements, and post-closing obligations.",
    },
  },
  {
    slug: "intellectual-property-basics-entrepreneurs",
    title: "Intellectual Property 101: Patents, Copyrights, and Trade Secrets for Entrepreneurs",
    category: "Intellectual Property — Book 8",
    excerpt: "Patents, trademarks, copyrights, and trade secrets protect different things. Here's what each covers, what it costs to get, and how entrepreneurs typically use them.",
    date: "2026-08-09",
  },
  {
    slug: "llc-to-s-corp-conversion",
    title: "Switching from LLC to S-Corp: When the Tax Savings Are Real and When They Aren't",
    category: "Tax Planning & Accounting — Book 3",
    excerpt: "The LLC-to-S-corp conversion can save self-employment taxes once your net profit exceeds roughly $40,000-$50,000. Here's the math, the process, and the administrative cost.",
    date: "2026-08-09",
  },
  {
    slug: "llc-vs-s-corp-vs-c-corp",
    title: "LLC vs. S-Corp vs. C-Corp: Which One Should You Actually Pick?",
    category: "Business Structure & Jurisdiction — Book 1",
    excerpt: "A plain-language guide to choosing between an LLC, S-Corp, and C-Corp for your new business. Covers taxes, liability, flexibility, and which entity structure fits your situation.",
    date: "2026-03-31",
  },
  {
    slug: "non-competes-after-ftc",
    title: "Non-Compete Agreements After the FTC Rule Changes: Where Things Actually Stand",
    category: "Managing Your Team — Book 6",
    excerpt: "The FTC's non-compete ban is blocked — but state law has changed significantly in parallel. Where things actually stand in mid-2026, and what small business owners need to know about protecting their legitimate interests.",
    date: "2026-06-30",
  },
  {
    slug: "obbba-small-business-owners",
    title: "The One Big Beautiful Bill Act: What Small Business Owners Need to Know",
    category: "Tax Planning & Accounting — Books 3 & 11",
    excerpt: "The OBBBA is the most significant federal tax legislation since TCJA 2017. Here's what small business owners need to understand about bonus depreciation, QSBS, and pass-through deductions.",
    date: "2026-07-07",
  },
  {
    slug: "offshore-accounts-legal-illegal",
    title: "Offshore Accounts: What's Legal, What's Not, and What the Penalties Actually Look Like",
    category: "Offshore Business, Tax Havens & International Trusts — Book 12",
    excerpt: "Holding offshore accounts is legal. Failing to report them is where the catastrophic penalties live. The compliance regime every U.S. person with foreign accounts needs to understand.",
    date: "2026-04-27",
    relatedBook: {
      title: "The Entrepreneur's Guide to Offshore Business, Tax Havens & International Trusts — Book 12",
      description: "U.S. tax residency, FBAR and FATCA compliance, foreign entity reporting, the major offshore jurisdictions, anti-deferral regimes, and the realistic landscape of international tax planning for U.S. persons. Part of The Million Dollar Highway series from Silverton Publishing.",
    },
  },
  {
    slug: "operating-agreement-vs-shareholder-agreement",
    title: "Operating Agreement vs. Shareholder Agreement: Which Does Your Business Need?",
    category: "Contracts & Legal Foundations — Book 2",
    excerpt: "Operating agreements govern LLCs. Shareholder agreements govern corporations. Here's what each covers, when you need both, and what happens without one.",
    date: "2026-08-09",
  },
  {
    slug: "personal-guarantees-business-loans",
    title: "Personal Guarantees on Business Loans: What You're Really Signing",
    category: "Business Financing — Book 9",
    excerpt: "The personal guarantee on a business loan is the most consequential signature most founders ever provide. What it actually obligates, what can be limited, and what almost never can.",
    date: "2026-04-27",
    relatedBook: {
      title: "The Entrepreneur's Guide to Business Financing — Book 9",
      description: "Commercial lending mechanics, collateral, covenants, SBA programs, lines of credit, asset-based lending, factoring, and the full landscape of small-business debt capital. Part of The Million Dollar Highway series from Silverton Publishing.",
    },
  },
  {
    slug: "protect-your-brand-trade-dress",
    title: "How to Protect Your Brand: Trade Dress, Logos, and Common Law Rights",
    category: "Intellectual Property — Book 8",
    excerpt: "Most small business owners don't realize they likely have enforceable brand rights without registration. A practical overview of common law trademark, federal registration, and trade dress protection.",
    date: "2026-06-30",
    relatedBook: {
      title: "Intellectual Property — Book 8",
      description: "Covering trademarks, copyrights, trade secrets, and protecting the assets that distinguish your business.",
    },
  },
  {
    slug: "qsbs-qualified-small-business-stock",
    title: "Qualified Small Business Stock (QSBS): The Exit Tax Benefit Most Business Owners Don't Know About",
    category: "Selling Your Business — Book 11",
    excerpt: "Section 1202 allows founders to exclude up to 100% of capital gains on QSBS from federal income tax — up to $10 million or 10x basis. Most business owners don't know it exists or might apply to them.",
    date: "2026-07-14",
    relatedBook: {
      title: "Exit Planning — Book 11",
      description: "Covers business exit planning — entity structure for exits, sale structure (asset vs. stock), earnouts, and post-closing considerations.",
    },
  },
  {
    slug: "scorp-vs-ccorp-when-to-switch",
    title: "S-Corp vs C-Corp: When It Might Be Time to Switch",
    category: "Business Structure & Jurisdiction — Books 1 & 11",
    excerpt: "For most small businesses, pass-through taxation is the right structure. But if you're planning an exit in the next 5–10 years, the QSBS analysis may favor converting to a C-corp. Here's the math.",
    date: "2026-07-07",
  },
  {
    slug: "tax-deductions",
    title: "Business Tax Deductions Most Small Businesses Miss",
    category: "Tax Planning & Accounting — Book 3",
    excerpt: "The difference between an average small business owner and one who understands the tax code is often $5,000-$15,000 in lost deductions every year. Here are the legitimate write-offs most owners leave on the table.",
    date: "2026-05-26",
    relatedBook: {
      title: "Tax Planning & Accounting — Book 3",
      description: "Detailed guidance on tax planning, entity structures, and financial management for small businesses. Part of The Million Dollar Highway series from Silverton Publishing.",
    },
  },
  {
    slug: "trademark-domain-name-protection",
    title: "Do I Need to Trademark My Domain Name? The Strategy Most Entrepreneurs Get Wrong",
    category: "Intellectual Property — Book 8",
    excerpt: "Most entrepreneurs waste money registering every domain extension. A federal trademark does most of that work for you. Here's the strategy that actually protects your brand online—and what it doesn't cover.",
    date: "2026-04-06",
    relatedBook: {
      title: "The Entrepreneur's Guide to Intellectual Property — Book 8",
      description: "Trademarks, domain names, trade secrets, patents, copyright, and IP in business transactions. Part of The Million Dollar Highway series from Silverton Publishing.",
    },
  },
  {
    slug: "trademark-registration",
    title: "When to Register a Trademark for Your Business",
    category: "Intellectual Property — Book 8",
    excerpt: "You automatically gain common law trademark rights when you start using a business name in commerce. But those rights are limited. Federal registration turns regional protection into nationwide protection.",
    date: "2026-05-26",
    relatedBook: {
      title: "Intellectual Property — Book 8",
      description: "In-depth discussion of intellectual property protection, licensing strategies, and building defensible business assets. Part of The Million Dollar Highway series from Silverton Publishing.",
    },
  },
  {
    slug: "what-business-insurance-do-i-need",
    title: "What Business Insurance Do I Actually Need?",
    category: "Business Insurance & Risk Management — Book 4",
    excerpt: "Which business insurance policies do you actually need? General liability, professional liability, workers comp, BOP, D&O — explained in plain language for small business owners.",
    date: "2026-03-31",
    relatedBook: {
      title: "Volume 4: Business Insurance & Risk Management",
      description: "Covering every insurance type, how to read a policy, what exclusions to watch for, and how to structure coverage as your business grows.",
    },
  },
  {
    slug: "what-should-be-in-every-business-contract",
    title: "What Should Be in Every Business Contract? A Founder's Clause-by-Clause Guide",
    category: "Contracts & Legal Foundations — Book 2",
    excerpt: "The 12 clauses every business contract needs — from performance and payment terms to indemnity, limitation of liability, and dispute resolution. A plain-language guide for entrepreneurs.",
    date: "2026-03-31",
    relatedBook: {
      title: "Volume 2: Contracts & Legal Foundations",
      description: "A clause-by-clause deep dive into every contract provision entrepreneurs encounter, with practical negotiation guidance for each.",
    },
  },
  {
    slug: "when-is-my-business-liable-for-ai",
    title: "Is My Business Liable When AI Gets It Wrong? An Entrepreneur's Guide to AI Legal Risk",
    category: "Technology, AI & Digital Business — Book 7",
    excerpt: "There is no federal AI liability statute, which does not mean there is no AI liability. A practitioner's guide to where entrepreneur legal exposure actually lies — and how to reduce it.",
    date: "2026-04-20",
    relatedBook: {
      title: "The Entrepreneur's Guide to Technology, AI & Digital Business — Book 7",
      description: "AI legal liability and governance, privacy law, intellectual property in the digital economy, digital contracts, platform risk, cybersecurity compliance, fintech, and health tech. Part of The Million Dollar Highway series from Silverton Publishing.",
    },
  },
  {
    slug: "when-to-elect-s-corp-status",
    title: "When Should Your LLC Elect S Corp Status? The Tax Math That Actually Matters",
    category: "Tax Planning & Accounting — Book 3",
    excerpt: "An S corp election can save an LLC owner $5,000 to $20,000+ per year in self-employment taxes—but only above a certain income level. Here's the calculation every profitable LLC owner should run.",
    date: "2026-04-06",
    relatedBook: {
      title: "The Entrepreneur's Guide to Taxes & Accounting — Book 3",
      description: "Entity elections, S corp mechanics, pass-through taxation, estimated taxes, and the tax strategy decisions every entrepreneur should make at formation and as the business scales. Part of The Million Dollar Highway series from Silverton Publishing.",
    },
  },
  {
    slug: "year-end-tax-planning-small-business",
    title: "End-of-Year Tax Planning for Small Business Owners: What to Do Before December 31",
    category: "Tax Planning & Accounting — Book 3",
    excerpt: "Tax planning after December 31 is compliance. Tax planning before December 31 is reduction. Here's what small business owners should be doing in Q4 — and why the timing matters.",
    date: "2026-07-14",
    relatedBook: {
      title: "Volume 3 of The Million Dollar Highway",
      description: "Covers tax strategy for small business owners — quarterly estimated taxes, deduction planning, entity-level elections, and working effectively with your CPA.",
    },
  },
];
